export { FightAPI, FightAPIError, DEFAULT_BASE_URL, LIVE_WS_URL } from './client';
export type { FightAPIOptions, Query, QueryValue } from './client';
export { VERSION } from './version';
export type * from './types';
/** The generated OpenAPI path map, for anything the hand-written types above
 * do not cover. Regenerated by `pnpm gen:types` from apps/api/openapi.json. */
export type { paths, operations } from './schema';
